version: 1
context:
  default:
    decryptSecret:
      # fromEnv: SECRET
      fromName: git-secrets.example-default
    secrets:
      # Hallo Welt
      databaseHost: XqtaIDugxKyytK0JwujGV/QUtgrLExXyCSV8nruVFe1WsY5xERIUvw==
      databasePassword: ZEQB63bTLUuHTCGTyrQUgWO0v/sgTLPruNJaXohTwGW5Iq8QNx6/xevG
  production:
    decryptSecret:
      # fromEnv: SECRET
      fromName: git-secrets.example-production
    secrets:
      databasePassword: jMEPG1Ct6xF1SR4EXeVg6fbsYD41/SklDnIAOkQz/W476hZYGVjRTZI5nVrW
features:
  renderFiles:
    default:
      files:
        # Array of files
      - fileIn: .env.default.dist
        fileOut: .env
    production:
      files:
      - fileIn: .env.production.dist
        fileOut: .env
      - fileIn: k8s-prod-secret.yaml.tpl
        fileOut: k8s-prod-secret.yaml