# Check https://goreleaser.com/customization/env/
env:
  - GO111MODULE=on

# Check https://goreleaser.com/customization/hooks/
before:
  hooks:
    - go mod download

# Check https://goreleaser.com/customization/build/
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goarm: mips64
        gomips: hardfloat
    # Run upx after build finished
    hooks:
      post: ./upx.sh

# Check https://goreleaser.com/customization/archive/
archives:
  - name_template: "git-secrets_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64

project_name: git-secrets

# Check https://goreleaser.com/customization/homebrew/
brews:
  - homepage: 'https://github.com/benammann/git-secrets'
    description: 'Encrypt your secrets with style'
    folder: Formula
    commit_author:
      name: franzramadhan
      email: franzramadhan@gmail.com
    tap:
      owner: franzramadhan
      name: homebrew-go-example