# Specifies the config schema version
version: 1

# You can specify multiple contexts, for example default, dev, prod
# The default context is required and should define all secrets
# The other context is merged into the default context
context:
  # The Default Context
  default:
    # The Secret Name to use
    # You can also pass the secret directly via --secret <secret> --secret-name <secret-name> or --secret-from-env <env-variable-name>
    decryptSecret:
      # You can either specify a name of the secret configured at ~/.git-secrets.yaml
      fromName: git-secrets-default
      # Our you configure an env variable to decode the secret
      fromEnv: 'MY_ENV_VARIABLE'
      # You can always overwrite this option via --secret <secret> --secret-name <secret-name> or --secret-from-env <env-variable-name>
    # Key Value Pair
    secrets:
      # Key: Key of the Secret, Value: The encrypted value
      databasePassword: <encrypted-value>
  # The Production Context
  # Overwrites the default context of you pass -c production
  production:
    # The Secret Name to use
    # You can also pass the secret directly via --secret <secret> --secret-name <secret-name> or --secret-from-env <env-variable-name>
    decryptSecret:
      # You can either specify a name of the secret configured at ~/.git-secrets.yaml
      fromName: git-secrets-default
      # Our you configure an env variable to decode the secret
      fromEnv: 'MY_ENV_VARIABLE'
      # You can always overwrite this option via --secret <secret> --secret-name <secret-name> or --secret-from-env <env-variable-name>
    # Key Value Pair
    secrets:
      # Key: Key of the Secret, Value: The encrypted value
      databasePassword: <encrypted-value>
# Feature specific configs here
features:
  # The render files feature decodes the secrets and then renders them decoded to the output file
  # The GoLang Templating Language is used here
  renderFiles:
    # The Default files to render
    default:
      files:
        # Array of files
      - fileIn: .env.default.dist
        fileOut: .env
    production:
      files:
      - fileIn: .env.production.dist
        fileOut: .env
      - fileIn: k8s-prod-secret.yaml.tpl
        fileOut: k8s-prod-secret.yaml